name: SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important pour l’analyse

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # Ajoute les 2 lignes ci-dessous si SonarCloud ne retrouve pas automatiquement le projet :
        with:
          args: >
            -Dsonar.projectKey=JulienGrade_vscode
            -Dsonar.organization=juliengrade
            -Dsonar.c.file.suffixes=-
            -Dsonar.cpp.file.suffixes=-
            -Dsonar.objc.file.suffixes=-
            -Dsonar.exclusions=**/node_modules/**,**/out/**,**/dist/**,**/build/**,**/*.dart,**/*.c,**/*.cpp,**/*.m,**/*.mm,**/*.h
